version: "3.7"

services:
  curie-node-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev

    image: curie-node-server
    env_file:
      - ./server/config/dev.env
    container_name: curie-node-server
    command: npm run dev
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    networks:
      - curie-network

  curie-react-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev

    image: curie-react-client
    container_name: curie-react-client
    command: npm start
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - curie-node-server
    ports:
      - "3000:3000"
    networks:
      - curie-network

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - curie-network
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Admin123

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:Admin123@mongo:27017/
    networks:
      - curie-network
    depends_on:
      - mongo

networks:
  curie-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
